builds:
  - goos:
      - darwin
      - windows
      - linux
      - freebsd
      - arm64
      - arm
    goarch:
      - amd64
      - 386
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/jckuester/awsweeper/internal.version={{.Version}} -X github.com/jckuester/awsweeper/internal.commit={{.ShortCommit}} -X github.com/jckuester/awsweeper/internal.date={{.Date}}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip